/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { HealthRecord, HealthRecordInterface } from "../HealthRecord";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "cid",
        type: "bytes32",
      },
    ],
    name: "addDoctor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "doctorAddress",
        type: "address",
      },
    ],
    name: "isDoctorVerified",
    outputs: [
      {
        internalType: "bool",
        name: "doctorStatus",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610209806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630b13acdf1461003b578063f53cd9551461006b575b600080fd5b6100556004803603810190610050919061010d565b610087565b6040516100629190610155565b60405180910390f35b610085600480360381019061008091906101a6565b6100a7565b005b60006020528060005260406000206000915054906101000a900460ff1681565b50565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100da826100af565b9050919050565b6100ea816100cf565b81146100f557600080fd5b50565b600081359050610107816100e1565b92915050565b600060208284031215610123576101226100aa565b5b6000610131848285016100f8565b91505092915050565b60008115159050919050565b61014f8161013a565b82525050565b600060208201905061016a6000830184610146565b92915050565b6000819050919050565b61018381610170565b811461018e57600080fd5b50565b6000813590506101a08161017a565b92915050565b6000602082840312156101bc576101bb6100aa565b5b60006101ca84828501610191565b9150509291505056fea26469706673582212206b5b1dc949b08783b5b22a43c0265b8256a59ad993dcccdd36370e8250da294764736f6c63430008130033";

export class HealthRecord__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<HealthRecord> {
    return super.deploy(overrides || {}) as Promise<HealthRecord>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): HealthRecord {
    return super.attach(address) as HealthRecord;
  }
  connect(signer: Signer): HealthRecord__factory {
    return super.connect(signer) as HealthRecord__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HealthRecordInterface {
    return new utils.Interface(_abi) as HealthRecordInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HealthRecord {
    return new Contract(address, _abi, signerOrProvider) as HealthRecord;
  }
}
