/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDoctor, IDoctorInterface } from "../IDoctor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "cid",
        type: "bytes32",
      },
    ],
    name: "addDoctor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDoctor__factory {
  static readonly abi = _abi;
  static createInterface(): IDoctorInterface {
    return new utils.Interface(_abi) as IDoctorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDoctor {
    return new Contract(address, _abi, signerOrProvider) as IDoctor;
  }
}
