/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDoctorRegistry,
  IDoctorRegistryInterface,
} from "../IDoctorRegistry";

const _abi = [
  {
    inputs: [],
    name: "addDoctor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDoctorRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDoctorRegistryInterface {
    return new utils.Interface(_abi) as IDoctorRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDoctorRegistry {
    return new Contract(address, _abi, signerOrProvider) as IDoctorRegistry;
  }
}
