/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IHealthRecord, IHealthRecordInterface } from "../IHealthRecord";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "cid",
        type: "bytes32",
      },
    ],
    name: "addDoctor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IHealthRecord__factory {
  static readonly abi = _abi;
  static createInterface(): IHealthRecordInterface {
    return new utils.Interface(_abi) as IHealthRecordInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHealthRecord {
    return new Contract(address, _abi, signerOrProvider) as IHealthRecord;
  }
}
