/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILender, ILenderInterface } from "../ILender";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EthReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "principalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "dateOfLoan",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "loanMaturityDate",
        type: "uint256",
      },
    ],
    name: "LoanBorrowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenCollateralAddress",
        type: "address",
      },
    ],
    name: "LoanRepaid",
    type: "event",
  },
];

export class ILender__factory {
  static readonly abi = _abi;
  static createInterface(): ILenderInterface {
    return new utils.Interface(_abi) as ILenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILender {
    return new Contract(address, _abi, signerOrProvider) as ILender;
  }
}
