/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILender, ILenderInterface } from "../ILender";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "nftCollateralAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nftCollateralTokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "principalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "dateOfLoan",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "loanMaturityDate",
        type: "uint256",
      },
    ],
    name: "LoanBorrowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "nftCollateralAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nftCollateralTokenId",
        type: "uint256",
      },
    ],
    name: "LoanRepaid",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nftCollateralAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountToBorrow",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getBorrowerByIndex",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrowerAddress",
        type: "address",
      },
    ],
    name: "getBorrowerIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBorrowers",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrowerAddress",
        type: "address",
      },
    ],
    name: "repayLoan",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILender__factory {
  static readonly abi = _abi;
  static createInterface(): ILenderInterface {
    return new utils.Interface(_abi) as ILenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILender {
    return new Contract(address, _abi, signerOrProvider) as ILender;
  }
}
