/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITTBank, ITTBankInterface } from "../ITTBank";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "accountNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "accountName",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startingBalance",
        type: "uint256",
      },
    ],
    name: "AccountOpened",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "accountNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "accountName",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newBalance",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "accountNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "accountName",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newBalance",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
];

export class ITTBank__factory {
  static readonly abi = _abi;
  static createInterface(): ITTBankInterface {
    return new utils.Interface(_abi) as ITTBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITTBank {
    return new Contract(address, _abi, signerOrProvider) as ITTBank;
  }
}
