/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ILenderInterface extends ethers.utils.Interface {
  functions: {
    "borrow(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "borrow",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;

  events: {
    "LoanBorrowed(address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "LoanRepaid(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoanBorrowed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanRepaid"): EventFragment;
}

export type LoanBorrowedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
    borrower: string;
    nftCollateralAddress: string;
    nftCollateralTokenId: BigNumber;
    principalAmount: BigNumber;
    dateOfLoan: BigNumber;
    loanMaturityDate: BigNumber;
  }
>;

export type LoanRepaidEvent = TypedEvent<
  [string, string, string, BigNumber] & {
    borrower: string;
    payer: string;
    nftCollateralAddress: string;
    nftCollateralTokenId: BigNumber;
  }
>;

export class ILender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILenderInterface;

  functions: {
    borrow(
      nftCollateralAddress: string,
      tokenId: BigNumberish,
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  borrow(
    nftCollateralAddress: string,
    tokenId: BigNumberish,
    amountToBorrow: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    borrow(
      nftCollateralAddress: string,
      tokenId: BigNumberish,
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "LoanBorrowed(address,address,uint256,uint256,uint256,uint256)"(
      borrower?: null,
      nftCollateralAddress?: null,
      nftCollateralTokenId?: null,
      principalAmount?: null,
      dateOfLoan?: null,
      loanMaturityDate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        borrower: string;
        nftCollateralAddress: string;
        nftCollateralTokenId: BigNumber;
        principalAmount: BigNumber;
        dateOfLoan: BigNumber;
        loanMaturityDate: BigNumber;
      }
    >;

    LoanBorrowed(
      borrower?: null,
      nftCollateralAddress?: null,
      nftCollateralTokenId?: null,
      principalAmount?: null,
      dateOfLoan?: null,
      loanMaturityDate?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        borrower: string;
        nftCollateralAddress: string;
        nftCollateralTokenId: BigNumber;
        principalAmount: BigNumber;
        dateOfLoan: BigNumber;
        loanMaturityDate: BigNumber;
      }
    >;

    "LoanRepaid(address,address,address,uint256)"(
      borrower?: null,
      payer?: null,
      nftCollateralAddress?: null,
      nftCollateralTokenId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      {
        borrower: string;
        payer: string;
        nftCollateralAddress: string;
        nftCollateralTokenId: BigNumber;
      }
    >;

    LoanRepaid(
      borrower?: null,
      payer?: null,
      nftCollateralAddress?: null,
      nftCollateralTokenId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      {
        borrower: string;
        payer: string;
        nftCollateralAddress: string;
        nftCollateralTokenId: BigNumber;
      }
    >;
  };

  estimateGas: {
    borrow(
      nftCollateralAddress: string,
      tokenId: BigNumberish,
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    borrow(
      nftCollateralAddress: string,
      tokenId: BigNumberish,
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
