/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ITTBankInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "AccountOpened(uint256,address,uint256)": EventFragment;
    "Deposit(uint256,address,uint256,uint256)": EventFragment;
    "Withdraw(uint256,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountOpened"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export type AccountOpenedEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    accountNumber: BigNumber;
    accountName: string;
    startingBalance: BigNumber;
  }
>;

export type DepositEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber] & {
    accountNumber: BigNumber;
    accountName: string;
    depositAmount: BigNumber;
    newBalance: BigNumber;
  }
>;

export type WithdrawEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber] & {
    accountNumber: BigNumber;
    accountName: string;
    withdrawAmount: BigNumber;
    newBalance: BigNumber;
  }
>;

export class ITTBank extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITTBankInterface;

  functions: {};

  callStatic: {};

  filters: {
    "AccountOpened(uint256,address,uint256)"(
      accountNumber?: null,
      accountName?: null,
      startingBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        startingBalance: BigNumber;
      }
    >;

    AccountOpened(
      accountNumber?: null,
      accountName?: null,
      startingBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        startingBalance: BigNumber;
      }
    >;

    "Deposit(uint256,address,uint256,uint256)"(
      accountNumber?: null,
      accountName?: null,
      depositAmount?: null,
      newBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        depositAmount: BigNumber;
        newBalance: BigNumber;
      }
    >;

    Deposit(
      accountNumber?: null,
      accountName?: null,
      depositAmount?: null,
      newBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        depositAmount: BigNumber;
        newBalance: BigNumber;
      }
    >;

    "Withdraw(uint256,address,uint256,uint256)"(
      accountNumber?: null,
      accountName?: null,
      withdrawAmount?: null,
      newBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        withdrawAmount: BigNumber;
        newBalance: BigNumber;
      }
    >;

    Withdraw(
      accountNumber?: null,
      accountName?: null,
      withdrawAmount?: null,
      newBalance?: null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber, BigNumber],
      {
        accountNumber: BigNumber;
        accountName: string;
        withdrawAmount: BigNumber;
        newBalance: BigNumber;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
